apiVersion: apps/v1
kind: Deployment
metadata:
  name: refillapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RefillApi
  template:
    metadata:
      labels:
        app: RefillApi
    spec:
      containers:
      - name: refillapirepos
        image: samplecr1.azurecr.io/refillapirepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: refillapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: RefillApi